version: "3"

networks:
  traffic-wizard-network:
    name: traffic-wizard-network
    driver: bridge

services:
  loadbalancer:
    build: "./loadbalancer"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./server:/server
    image: traffic-wizard-lb
    ports:
      - "5000:5000"
    privileged: true
    networks:
      - traffic-wizard-network
